<?php
class SessionKeyConstants {
	const  	USER_LOGIN_INFO = "USER_LOGIN_INFO";
	const 	APP_CSRF = "APP_CSRF";
	const 	STATUS_MESSAGE = "STATUS_MESSAGE";

	//const 	PROJECT_FILE_NAME_UPLOAD_PDF = "PROJECT_FILE_NAME_UPLOAD_PDF";
	//const   PROJECT_FILE_NAME_UPLOAD_CSV = "PROJECT_FILE_NAME_UPLOAD_CSV";
}
?>