<?php


class index extends default_admin_class
{
    var $before_date_y;

    function __construct()
    {
        parent::__construct();
    }

    function main(){
        ?>
        <!--Body content-->
        <div id="content" class="clearfix">
			<div class="contentwrapper"><!--Content wrapper-->
				<div class="heading">
					<h3>管理画面</h3>
					<div class="resBtnSearch">
						<a href="#"><span class="icon16 icomoon-icon-search-3"></span></a>
					</div>

				</div><!-- End .heading-->


                </div>
                </div>
        <?php
    }

}